### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by lupo1st** [Blazam-App/BLAZAM#130]
Hi,
i have installed it manually.
On the first try to open the install-process starts and after creating the database it stops. Step 2 doesn's start...

What could be the issue?

I'm running it on a Windows Server 2022 / IIS/ Database is on an external NAS

Any idea???

**Comment by jacobsen9026** [comment]
Hello,

What is the database type you are running on your NAS? I'm guessing it's MySQL or MariaDB and not SQL based.

Does the installer indicate that the database gets installed, or does it endlessly let you attempt to install the database?

If you could, please post the database log file found in C:\Windows\Temp\Blazam\writable\logs\database. Ideally this would be a single file from a single run of a fresh install attempt.

Turning on debug mode will also help locate the bug. This can be done in the config by changing "DebugMode" to "true". Then any errors are shown in the browser console in real time.

Thanks.

**Comment by lupo1st** [comment]
Hi jacobsen9026,

it is a MySQL - Database
It creates the database and then stops. I can see the database on the MySQL Server.

[db2023082314_006.txt](https://github.com/Blazam-App/BLAZAM/files/12419166/db2023082314_006.txt)

Thanks

**Comment by jacobsen9026** [comment]
Thanks, I've done minimal testing with MySQL running SQL server myself. Looking through the log now.

**Comment by jacobsen9026** [comment]
I also may have introduced a bug when I went to multi-database type support. Try just restarting the website in IIS, it might be a UI bug I'm aware of that can cause the 2nd step to require a restart of the application to be reachable.

**Comment by lupo1st** [comment]
I have restarted the website but it didn't get any further.
I tried to connect to MariaDb running on Port 3308, but connection wasn't possible. 
Only on Standardport 3306 (i'running two instances of MariaDB - 5.5. and 10).

**Comment by lupo1st** [comment]
I have tried it with SQLite... i now reach Step 3 but the credentials are not accepted. 
I used the Admin. But it keeps crossed out at the bottom. Port is open

**Comment by lupo1st** [comment]
Is Ldaps required or can you use LDAP connection?

**Comment by jacobsen9026** [comment]
The last three weeks were my busy time at work, and I really only get time to work on this there. I'll start working on a new update soon.

The install wizard on first launch is buggy, it was the first thing I made and I failed to provide it the quality it deserves.

Put in what you believe are the correct settings and credentials. LDAP is fine, LDAPS would require trusting the certificate authority to make a connection.

The "checker" at the bottom of that setup page does not retry after failures, it gets stuck. Restarting the web server at this step after saving LDAP settings should show you the true impact of those settings. Sorry for the muckiness.

**Comment by jacobsen9026** [comment]
I have yet to test the initial install with MySQL again, I'm suspecting some sort of database compatibility error based on how I am setting it up for MSSQL and SQLite.

**Comment by lupo1st** [comment]
I finally got it running, but i don't see any Users and when i want to browse i get the following picture:

![image](https://github.com/Blazam-App/BLAZAM/assets/101975344/95d05bbc-5bc8-4921-9a7a-ae0452608b8e)

**Comment by jacobsen9026** [comment]
I've been testing against MariaDB for the latest nightly update. Releasing a new Nightly today which you may want to try.

Was the error above when logged in as the local Admin account?

**Comment by lupo1st** [comment]
The error occured when i was logged in as an Domain Admin.

**Comment by lupo1st** [comment]
Is there a precompiled Version of the Nightly Build available?

**Comment by jacobsen9026** [comment]
> Is there a precompiled Version of the Nightly Build available?

It's in the releases. That error is indicating some type of issue getting the domain admin account you logged in as. I only know of 4 AD environments this app has been used in so far (2 mine, one German, and yours) so it's quite possible there is some nuance going on. 



Based on logs I'm seeing no connection to Active Directory, but you **can** login, so your setting seem correct. 

How is it with the built-in admin?

The installation only passes when a connection is successful, did you change any Active Directory settings after finishing install?

Thank you for your interest and tolerance to my work schedule. Things are quiet again at work, so expect near daily updates on Nightly. Self update might even work now on most installs. I usually get the most progress November-Feb.

**Comment by jacobsen9026** [comment]
Stable got updated today, so you don't need the nightly.

**Comment by lupo1st** [comment]
Hi jacobsen,

i reinstalled everything and it almost works... 

Opening a User gives me an error

i have the following issue on the settings page

![image](https://github.com/Blazam-App/BLAZAM/assets/101975344/8b354b9d-41a1-4203-919c-da3dd4103d72)

Opening the Bin crashes 

... but we are getting closer

**Comment by jacobsen9026** [comment]
Thanks lupo1st,

The issue on the settings page is expected for Update with no manual configuration. I've updated the documentation for setup of self-update. https://docs.blazam.org/update/self/#setup

When opening a user, I may not be getting all the error logs, but I am seeing....

System.FormatException: String '11.16.2023 09:23:10Z' was not recognized as a valid DateTime.
   at System.DateTime.Parse(String s)
   at BLAZAM.ActiveDirectory.Adapters.DirectoryEntryAdapter.get_LastChanged() in D:\a\BLAZAM\BLAZAM\BLAZAMActiveDirectory\Adapters\DirectoryEntryAdapter.cs:line 325
   at BLAZAM.Pages.Users.ViewUser.<>c__DisplayClass0_0.<BuildRenderTree>b__42(RenderTreeBuilder __builder9)
   at MudBlazor.MudStack.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)

Which is likely due your dates being Day/Month/Year and there is no 16th month. So I must have made an error in ensuring it is converted the correct way for other locales. However, this is not a breaking error, and should not prevent the page from displaying. I've also got to catch up on my translations.

Since we're this far, I'm going to suggest the following...

1. Open appsettings.json in the install directory  ("C:\inetpub\Blazam")
2. [Enable DebugMode by changing the value to "True" ](https://docs.blazam.org/install/config/#debugmode)
3. Restart the website
4. Navigate to a user, errors will be sent to the browser console
5. After the error, open Developer Tools on the browser (usually F12)
6. Switch to the "Console" tab of the Dev Tools
7. Paste any error text that looks similar to what I've pasted above in this post.
8. Perform steps 4-7 but when trying to open the Bin

If no error's are produced in the Console, please share a screenshot of the page in error, please remove sensitive data if shown.

**Comment by lupo1st** [comment]
![image](https://github.com/Blazam-App/BLAZAM/assets/101975344/3ec288ad-f099-471d-a20d-7897c7a36bef)

This is what i get when opening a User

**Comment by lupo1st** [comment]
_ updated to the nightly build and now get this Error

![image](https://github.com/Blazam-App/BLAZAM/assets/101975344/74b3fdc3-6c9d-4f9d-ac2c-da2ad5258ba5)

Exactly what you were talking about
_

**Comment by jacobsen9026** [comment]
Apparently that international Date conversion is a breaking error, I'm on it. I'll let you know when I have a fix.

**Comment by jacobsen9026** [comment]
Patched in latest nightly

**Comment by lupo1st** [comment]
Good Work!!! 

Tested it and it works on most points... probably i am doing something wrong.

I still get an Error after selecting a User ... any idea why?

![image](https://github.com/Blazam-App/BLAZAM/assets/101975344/7ac09dec-3bb6-41e4-9e2c-baef9f6226de)

**Comment by jacobsen9026** [comment]
So I'm not sure if this is going to cause missing data, but a fix for this latest error is now in the Nightly.

When testing latest Nightly, please make sure all groups a user is a member of are shown.

**Comment by lupo1st** [comment]
Great work... this is fine...
no i have an error when adding a new User

Something about the path
![image](https://github.com/Blazam-App/BLAZAM/assets/101975344/d301e713-95cf-4137-a3e9-9261adbc37c7)

**Comment by jacobsen9026** [comment]
Hi @lupo1st 
The template user creation is the most beta feature. It still has many bugs. You're bug reports are, and will be extremely helpful to the app. Thank you.

For this bug, I'll probably need to add some more error logging details and have you try again when I update Nightly. We have a holiday in the US tomorrow so an update won't be out until the next day.

Until then, some answers to the following questions will be helpful:

- Does this template inherit another template?
- Could you please provide a screenshot of the template settings for the template used (remove password if set)?
- Lastly, did you set the Active Directory Server in settings to be a specific DC or the domain DNS name?

Thanks again.

**Comment by lupo1st** [comment]
I'm back... was on a trip..

1. No
2. I hope this is the one you are asking for 
 
![image](https://github.com/Blazam-App/BLAZAM/assets/101975344/19ac406e-9f64-48fb-a4c9-f6d6635bc594)
![image](https://github.com/Blazam-App/BLAZAM/assets/101975344/ebe65540-16a7-4906-a722-25a500b1b865)


3. I set a specific DC...

**Comment by jacobsen9026** [comment]
Of course, life came up on me and I had a lot less time to work on this. I got a bunch of personal problems in life all lining up at the same time and a major unexpected hire I need to make at work.

I'm not even sure I updated the nightly with my logging to capture the data I needed... I've released a new nightly which can be updated to. It includes a couple of new features including favorites, printer improvements, and a big upgrade to the online computer pages. It also has the additional logging I need.

**Comment by lupo1st** [comment]
No Problem, life is always surprising and i am thankful for your work. I updated the nightly and look forward for improvements.

**Comment by jacobsen9026** [comment]
So there's some new thing going on with your install, not sure if there is a DB issue, but the reading the apps cache for forcing HTTPS is failing. Patch published.

**Comment by lupo1st** [comment]
So far everything i tested except for the New User is working.. Great Job

**Comment by jacobsen9026** [comment]
Thank you, and there was a bug introduced that prevented edits from being saved that has since been patched in the latest nightly 0.8.7.2024.1.17.1902

Continuing to investigate new user issue...

**Comment by lupo1st** [comment]
Had to reintsall everything due to a server problem, but now it looks good. Templates don't work well as i can see. Not all predefinded fields are editable. Username is filled radomly.

Thank you

**Comment by jacobsen9026** [comment]
Update for templates and user creation is in the works, a few more things to refine and it'll be released to everyone as a stable

**Comment by jacobsen9026** [comment]
With the release of 0.8.9 how are the templates working for you?

2 known issues, users are created in a disabled state, and password setting is delayed

I've been setting up my templates at work and have been using them nearly daily to create new users.

**Comment by jacobsen9026** [comment]
Gonna assume all is well. Feel free to re-open or create a new issue anytime. Thank you for your feedback.

**Comment by lupo1st** [comment]
Dear jacobsen,
thank you for your incredible work. I was pretty busy with work,so i couldn't keep an eye on this. By now i can tell that it is working fine so far.
