### ISSUE TITLE
"BLAZAMSession : System.NullReferenceException" Stack Trace: at BLAZAM.Session.ApplicationNewsService.

### ISSUE THREAD

**Issue by swamipurnamsha** [Blazam-App/BLAZAM#276]
The Blazor application encounters an error "BLAZAMSession : System.NullReferenceException" 

"Error Message: Object reference not set to an instance of an object.
Stack Trace:
at BLAZAM.Session.ApplicationNewsService.<>c__DisplayClass12_0.b__0(NewsItem x) in D:\a\BLAZAM\BLAZAM\BLAZAMSession\ApplicationNewsService.cs:line 62"

I am running the Blazam App using IIS with all the .Net dependencies installed and using a MySQL database, we have configured the active directory and finalized the installation. After the installation the page results in the same error mentioned earlier "BLAZAMSession : System.NullReferenceException"

The Blazor WebAssembly application should not throw an exception related to the "applications news service" not able to be handled. 

Within the IIS authentication configuration, it is set to allow Anonymous Authentication and the .Net Authorization is set to Allow All Users. 

For additional troubleshooting:  Within the Blazam application directory the IIS_IUSRS and IUSR have been granted full control of the Blazam root directory.

ApplicationPool is set to AlwayRunning and have Set IIS Site to Preload true

OS: Windows Server 2022
Browser: Edge
Version: 122.0.2365.92
Blazam version: 0.8.9.2024.02.28.0056

![image](https://github.com/Blazam-App/BLAZAM/assets/164919767/ec34e0e5-2380-4d0a-b9c0-753ad5d9278c)
.

![image](https://github.com/Blazam-App/BLAZAM/assets/164919767/abc9490e-6be8-4eb8-b242-f552be1ce71a)

**Comment by jacobsen9026** [comment]
Thank you for the report, brand new feature, not surprised. I kind of rushed it since I had no existing update notification feature.

Will be patched in next release, which I will make sure to release by Saturday (was  about to release an update anyway, but gotta give some testing time for other changes).

**Comment by jacobsen9026** [comment]
This should be fixed in the Stable version released today. If you used the Web Installer, running it again and choosing Update will update Blazam.

**Comment by swamipurnamsha** [comment]
@jacobsen9026 

I see that the error output shows that some part of this code is fixed however, a new error output is being thrown for the same ApplicationNewsService.cs, image attached:

Something terrible has happened...
BLAZAMSession : System.NullReferenceException
Error Message: Object reference not set to an instance of an object.
Stack Trace:
at BLAZAM.Session.ApplicationNewsService.GetUnreadNewsItems(IApplicationUserState user) in D:\a\BLAZAM\BLAZAM\BLAZAMSession\ApplicationNewsService.cs:line 69

at BLAZAM.Gui.UI.Outputs.ApplicationNewsProvider.RefreshUnreadItems() in D:\a\BLAZAM\BLAZAM\BLAZAMGui\UI\Outputs\ApplicationNewsProvider.razor:line 111

at BLAZAM.Gui.UI.Outputs.ApplicationNewsProvider.RefreshItems() in D:\a\BLAZAM\BLAZAM\BLAZAMGui\UI\Outputs\ApplicationNewsProvider.razor:line 96

at BLAZAM.Gui.UI.Outputs.ApplicationNewsProvider.OnInitialized() in D:\a\BLAZAM\BLAZAM\BLAZAMGui\UI\Outputs\ApplicationNewsProvider.razor:line 92

at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

![image](https://github.com/Blazam-App/BLAZAM/assets/164919767/ce7d0c47-3087-45ea-834d-45a67109ecf5)
