### ISSUE TITLE
Creating users in AD with Non-Super blazam privelege results in an error output

### ISSUE THREAD

**Issue by swamipurnamsha** [Blazam-App/BLAZAM#308]
Hi again @jacobsen9026 

We have used the latest release version: 0.9.1.2024.04.13.2119 running as a service.

We encountered a bug while creating a user(custom method), using a non-superuser account in Blazam.
Please note that the feature works very well with super-user blazam accounts.
Null pointer exception occurs after clicking the "next" button as shown in the attached snippets.

[Error output video here](https://we.tl/t-jlGBTIxEeI)

![image](https://github.com/Blazam-App/BLAZAM/assets/164919767/fb320a2d-fb06-4c43-9b9d-958cc252b99d)
![image](https://github.com/Blazam-App/BLAZAM/assets/164919767/d9650fb0-189b-4b9e-801e-a89658f848ac)

**Comment by jacobsen9026** [comment]
This will be fixed in the next update

**Comment by jacobsen9026** [comment]
Sorry for the slight delay, saw a discussion someone opened a little too late and wanted to include their idea in this update.

0.9.2 released
