### ISSUE TITLE
Mapping computers to users

### ISSUE THREAD

**Issue by jacobsen9026** [Blazam-App/BLAZAM#318]
Will add more later

**Comment by jacobsen9026** [comment]
From @isha-arunnegi

> Regarding the mapping computers to users, is that for VDI? If not, please elaborate. Thank you.

Hi @jacobsen9026
It is not for VDI.
We just need a certain user to be able to log into only certain few computers in the domain.
In AD, when we go to a user details: there is "Log On To" button inside the tab: "Account". On clicking this button it opens up a text box where we can fill the computer names where this user is allowed to log in.
We are able to achieve this using Blazam, by adding the field "userWorkstations". It is working fine.

Thanks

**Comment by jacobsen9026** [comment]
My response:

I'm glad to hear that the custom fields allow you to do this, but I can understand the desire to have it pull the computer names from AD for you so you are not typing in workstation names manually.

I will add that to the list of features to be added to a future update. Possibly 0.9.3, probably 0.9.4

**Comment by isha-arunnegi** [comment]
Hi @jacobsen9026 

On the latest version we got this error when we open the website for the first time after installation (when it goes for database installation).
![blazam_error_may3](https://github.com/Blazam-App/BLAZAM/assets/150012363/c39607f1-a46d-4b45-8437-37a1909d65f3)

Can you please take a look?

**Will it be possible to post the previous release setup?**
I need this because, I removed the previous setup in order to try the new one and now I need to go back to the previous version.

Thanks

**Comment by jacobsen9026** [comment]
> Hi @jacobsen9026
> 
> On the latest version we got this error when we open the website for the first time after installation (when it goes for database installation). ![blazam_error_may3](https://private-user-images.githubusercontent.com/150012363/327660696-c39607f1-a46d-4b45-8437-37a1909d65f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDc5ODksIm5iZiI6MTcxNTEwNzY4OSwicGF0aCI6Ii8xNTAwMTIzNjMvMzI3NjYwNjk2LWMzOTYwN2YxLWE0NmQtNGI0NS04NDM3LTM3YTE5MDlkNjVmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxODQ4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjAwNjgwMzliOWUzZDc1MzBjYzExYjYwZDQ4Y2UxYjMyNThmNGQ3Nzg5MDU5MzI0NmEyM2QzZGZhNWZkM2E3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Mqu2ckLTzECN6r48Fv7XN0R3qaGE03ofoKY1zjoCFxE)
> 
> Can you please take a look?
> 
> **Will it be possible to post the previous release setup?** I need this because, I removed the previous setup in order to try the new one and now I need to go back to the previous version.
> 
> Thanks

I'm gonna try and publish a small hotfix patch later today for this, but if you install with web installer, and then afterwards extract this zip to the install directory it will be the previous version...

https://github.com/Blazam-App/BLAZAM/releases/download/Stable-v0.9.1.2024.04.13.2119/blazam-stable-v0.9.1.2024.04.13.2119.zip

**Comment by jacobsen9026** [comment]
Just wanted to clarify, that hotfix went out and the web installer will install/update to latest...

**Comment by isha-arunnegi** [comment]
Thanks @jacobsen9026 
We are trying the new fix. It seems to be working fine.
Thanks a lot

**Comment by isha-arunnegi** [comment]
Hi @jacobsen9026 
Just wanted to clarify that the new version is working fine.
Thanks a lot for the fix. :)
Thanks
