### ISSUE TITLE
Description is not shown under Group details when a group is displayed

### ISSUE THREAD

**Issue by isha-arunnegi** [Blazam-App/BLAZAM#362]
There are 2 features we would like to see in Blazam.
1. On clicking on a group name in Blazam, we see various details like group name, email address etc. But there is no group description. It will be very nice to have group description also. (Snapshot attached)
There may be a few groups with similar names in that case, when the user searches for a group (but he/she is not sure about the name of a group). The group description will be useful for identifying the correct group.
![groupdetails](https://github.com/Blazam-App/BLAZAM/assets/150012363/472bd489-7aa7-466b-b764-e893b3ddf6aa)

2. When a non-super user logs into Blazam and they perform a rename function, they can rename the username and e-mail ID but not first name, middle name, last name and display name. I checked in the access level
 (under permissions menu), there is no option to read/edit first name, middle name, last name, display name. 

![access_level_displayname missing](https://github.com/Blazam-App/BLAZAM/assets/150012363/af181185-91b1-41cf-a6d0-fb176029d3c5)
![rename](https://github.com/Blazam-App/BLAZAM/assets/150012363/d9da37b8-e995-4183-87d5-579b8ed5db2f)

Thanks in Advance :)

**Comment by jacobsen9026** [comment]
For number two, apparently I never finished. Requested features a patch away...

**Comment by jacobsen9026** [comment]
Thanks again for the valuable feedback, it's appreciated more than I can explain.

Everything in this issue has been addressed and will be included in the next update, due to release this week.

**Comment by isha-arunnegi** [comment]
Thanks a lot @jacobsen9026 :)
