### ISSUE TITLE
Additional fields are not editable through non-superuser account

### ISSUE THREAD

**Issue by isha-arunnegi** [Blazam-App/BLAZAM#366]
We have added a few additional fields in Blazam like: userWorkstations, uidNumber, gidNumber etc as shown in snippet:
![add_fields](https://github.com/Blazam-App/BLAZAM/assets/150012363/f81e7cf0-18b5-4264-81e4-846465b3e993)

When we try to edit thiese additional fields from a non-superuser account, these fields are not editable, though we have given the edit access from "Access Level" menu under "Permissions". snippets attached:
![permissions](https://github.com/Blazam-App/BLAZAM/assets/150012363/eb987331-fdb6-4edd-a9f7-036a21655553)

![disabled](https://github.com/Blazam-App/BLAZAM/assets/150012363/f2e07055-e78a-4710-a55f-669ea986ec8f)

**Comment by jacobsen9026** [comment]
Seriously helpful feedback. You are my favorite "client" by far. 

For a feature I knew needed to be included but don't actually use myself, I'm not surprised. I expect to find half written code on the path to full functionality. Looks like it should be a fairly easy fix on my end.

**Comment by jacobsen9026** [comment]
Literally needed to add " || !User.CanEditField(field)"
