### ISSUE TITLE
BalZam Login error

### ISSUE THREAD

**Issue by nenee-ai** [Blazam-App/BLAZAM#475]
Description:
When using BalZam, we encounter an error during the login process. The error message is:

Blazam error is: Unexpected character encountered while parsing value: <. Path '', line 0, position 0".

**Comment by jacobsen9026** [comment]
Hi @nenee-ai

Were you trying to log in with the built-in "admin" account?

I was not able to identify the error in our logging server... 

Is that the complete error message? If there is any more, please paste the complete error text in a reply.

Thank you

**Comment by nenee-ai** [comment]
Hello @jacobsen9026,

We can log in with the built-in admin account, but we are unable to log in using the delegated admin accounts. Please find the attached screenshot for reference.

Thank you.
![image (10)](https://github.com/user-attachments/assets/dc2169a3-df78-40a4-a5ee-177bb53e2c17)

**Comment by jacobsen9026** [comment]
I had a feeling... and that type of error is not reported to our error logging server. 

Can you please let me know all non-US alphanumeric characters (A-Z,a-z, 0-9) in the username, (eg: ò,-,{,Ä)?

This is most likely an internationalization bug.

**Comment by jacobsen9026** [comment]
> I had a feeling... and that type of error is not reported to our error logging server.
> 
> Can you please let me know all non-US alphanumeric characters (A-Z,a-z, 0-9) in the username, (eg: ò,-,{,Ä)?
> 
> This is most likely an internationalization bug.

If you're uncomfortable posting because most or all characters are non-US, you can email it to support@blazam.org and it will be kept private.

**Comment by nenee-ai** [comment]
Hello, 
Thank you. I sent the user name to your [support@blazam.org](mailto:support@blazam.org).

**Comment by jacobsen9026** [comment]
Thank you,
I was still unable to reproduce the error. The username is simple enough that it couldn't cause this, but I've removed some old unused JS code I believe could be a possible cause along with adding logging of the error to our log server so we can see more details.

This change will be included in the v1 release which will require .NET 8, due to drop by Monday.

I apologize for any inconvenience.

**Comment by nenee-ai** [comment]
Thank you. We will try debugging this, it could be some other problem.

**Comment by jacobsen9026** [comment]
Did you mean to close this issue?

The issue I thought I saw is not the likely cause.

And this looks like a legitimate JavaScript error.

**Comment by jacobsen9026** [comment]
Version 1.0 has been released with the logging additions I mentioned. Honestly not much else was changed to address this specific issue because I was unable to reproduce, but if the error remains, please let me know.

Thank you,
Chris
