### ISSUE TITLE
Flexible username templating

### ISSUE THREAD

**Issue by ErmakovDmitriy** [Blazam-App/BLAZAM#577]
**Is your feature request related to a problem? Please describe.**
Currrently, Blazam has a somewhat limited way to generate usernames, in particular,
one can use `{fn}`, `{ln}`, `{fi}`, `{li}` and a bit more.

**Describe the solution you'd like**
It might be a good idea to implement a more flexible templating, for instance:

- {fn[0-3]} to get the first  3 characters of the First Name (the same about the last name).
- Also, it might be a good idea to be able to use regular expression captures/replaces from fields like First Name, Last Name, Middle Name;
- An option to overwrite/modify the generated username, in case the auto-generated value is somewhat not nice (forms a rude word).

**Comment by jacobsen9026** [comment]
Hi,

These are some excellent suggestions.

> - {fn[0-3]} to get the first 3 characters of the First Name (the same about the last name).
> - Also, it might be a good idea to be able to use regular expression captures/replaces from fields like First Name, Last Name, Middle Name;
> - An option to overwrite/modify the generated username, in case the auto-generated value is somewhat not nice (forms a rude word).

1. Easy, flexible, and certain to be included
2. Regex is a bit of a beast, but I'll see how best it can be implemented, thinking something like {fn:regex:[command]}
3. Personally, I would want to control which templates can have the names overridden, so I will likely make your third suggestion as an "Allow Username Change" in each template (inheritable of course)

Please follow up with any additional feature you would like added regarding templates. If you have suggestions for other application functions, please create as a new GitHub issue.

Thank you.

**Comment by ErmakovDmitriy** [comment]
Hi!

Thank you for the fast response!

**Comment by jacobsen9026** [comment]
Thanks,
One question, how important is regex replace for you? It's a bit of a complication and will lead to pretty complex syntax due to the need for yet another parameter (up from 2 to 4 parameters per formula possible).

**Comment by ErmakovDmitriy** [comment]
The regex replace is not important for me, it was just an idea.

For me points 1 and 3 are important as I want to use names like: Dmitrii Ermakov => dmerm, for example and if such abbreviation produces a somewhat strange result to be able to "override" it.

**Comment by jacobsen9026** [comment]
It can be done, I think it might be useful for someone out there, but I'm failing to come up with an example of how it would be used. I think I'll leave it out for now and only do regex match to keep explanation of syntax simpler, instead of {fn:regex[match expression](replace with)} just {fn:regex[match expression]}

The first x characters feature is built and tested. Your example username would be written as {fn:l[2]}{ln:l[3]}

Here's the proposed syntax
![image](https://github.com/user-attachments/assets/057bdb0c-cb6c-462a-908f-17fa84aa4abf)

The override feature is today's objective.

**Comment by jacobsen9026** [comment]
Features 1 and 3 are implemented, super-admins can always change usernames.

Feature 2 is implemented for all except regex replace.

Will drop in version 1.0.5 today.
