### ISSUE TITLE
Microsoft.AspNetCore.Components : System.NullReferenceException

### ISSUE THREAD

**Issue by Tacoo99** [Blazam-App/BLAZAM#604]
**Describe the bug**
The bug appears when i want to edit or add widget after installing and configurating Blazam.

**To Reproduce (Required for complex issues)**
1.  Install Blazam as a service and SQLLite(just for testing) and of course ASP NET 8.0

**Screenshots**
![image](https://github.com/user-attachments/assets/397354ef-c0ad-40c2-aab7-b514fa4e6776)

**Environment (please complete the following information):**
 - Blazam Version: Latest(v1.0.6.2024.10.28.2301)
 - Running under Service

**Comment by Tacoo99** [comment]
Update:
Same problem appears with MariaDB SQL Database and MS SQL.
I can't run Blazam service after updating Net Core to 9.0 version - must downgrade to 8.0

**Comment by jacobsen9026** [comment]
I've identified the original problem and will have a fix released later today.

**Comment by Tacoo99** [comment]
Thank you so much, waiting for update from you :)

**Comment by jacobsen9026** [comment]
> Update: Same problem appears with MariaDB SQL Database and MS SQL. I can't run Blazam service after updating Net Core to 9.0 version - must downgrade to 8.0

I assumed 9 was backwards compatible, I have not tested though.

**Comment by Tacoo99** [comment]
> > Update: Same problem appears with MariaDB SQL Database and MS SQL. I can't run Blazam service after updating Net Core to 9.0 version - must downgrade to 8.0
> 
> I assumed 9 was backwards compatible, I have not tested though.

I can test it tomorrow and let you know with some logs of course.

How can I set your fix for Widgets to my Blazam installations on servers?
I have to wait for the next release or compile by myself?

**Comment by jacobsen9026** [comment]
About to drop, doing some final housekeeping and testing. Found a few additional issue that I was able to fix. ETA 15-30 mins.

You can update in app if you've set up folder permissions.

Otherwise if you installed by the web installer, it can update.

Lastly, you can download the zip when it drops on GitHub Releases and copy it over.

**Comment by jacobsen9026** [comment]
Update v1.0.7 has dropped.
