### ISSUE TITLE
Can't configure delegation / buttons freezed

### ISSUE THREAD

**Issue by Tacoo99** [Blazam-App/BLAZAM#615]
**Describe the bug**
After updating to latest version, delegating window freezes and I can't use it.

1. Just install and configure everything using web installer, IIS and MariaDB

**Screenshots**
![image](https://github.com/user-attachments/assets/2356164f-b54d-41b2-aa77-c9005c193dc5)

**Environment (please complete the following information):**
 - Blazam Version: Latest(v1.0.7.2024.10.30.0007)
 - Running under IIS(same problem with Service)

**Comment by Tacoo99** [comment]
And yes, I tried to do a *fresh* installation, same effect.

**Comment by Tacoo99** [comment]
**In previous release, delegation is working fine**

**Comment by jacobsen9026** [comment]
I have to laugh, I removed 2 lines of code, assuming it was being handled by third-party code, I was wrong, and introduced a memory leak.

The fix is currently in the dev branch for testing.

**Comment by Tacoo99** [comment]
> I have to laugh, I removed 2 lines of code, assuming it was being handled by third-party code, I was wrong, and introduced a memory leak.
> 
> The fix is currently in the dev branch for testing.

Great news, thank you and I look forward to the next release and testing.
